# Form implementation generated from reading ui file 'views/main_window.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(691, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.sideBar = QtWidgets.QListWidget(parent=self.centralwidget)
        self.sideBar.setEnabled(True)
        self.sideBar.setMaximumSize(QtCore.QSize(150, 16777215))
        self.sideBar.setBaseSize(QtCore.QSize(150, 0))
        self.sideBar.setObjectName("sideBar")
        self.horizontalLayout_2.addWidget(self.sideBar)
        self.content_stack = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.content_stack.setObjectName("content_stack")
        self.emp = QtWidgets.QWidget()
        self.emp.setObjectName("emp")
        self.content_stack.addWidget(self.emp)
        self.product = QtWidgets.QWidget()
        self.product.setObjectName("product")
        self.content_stack.addWidget(self.product)
        self.customer = QtWidgets.QWidget()
        self.customer.setObjectName("customer")
        self.content_stack.addWidget(self.customer)
        self.order = QtWidgets.QWidget()
        self.order.setObjectName("order")
        self.content_stack.addWidget(self.order)
        self.category = QtWidgets.QWidget()
        self.category.setObjectName("category")
        self.content_stack.addWidget(self.category)
        self.horizontalLayout_2.addWidget(self.content_stack)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 691, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
